version: "2.1"

services:
  mysql57:
    image: mysql:5.7
    container_name: mysql57
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  mysql80:
    image: mysql:8.0
    container_name: mysql80
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    links:
      - mysql57
    volumes:
      - .:/mysite
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - mysql57
      - mysql80
    restart: always
