version: "3.9"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    links:
      - db
    volumes:
      - .:/mysite
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
    restart: always

#  db:
#    image: mysql/mysql-server:5.7
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_PASSWORD: root
#      MYSQL_DATABASE: test_db
#      MYSQL_ROOT_HOST: '%'
#    command:
#      - "--default-authentication-plugin=mysql_native_password"
#    ports:
#      - '3306:3306'
#    expose:
#      - '3306'

  db:
    image: mysql/mysql-server:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_HOST: '%'
    command:
      - "--default-authentication-plugin=mysql_native_password"
    ports:
      - '3306:3306'
    expose:
      - '3306'
