# Generated by Django 3.2 on 2022-02-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteBoxStudentsExaminationDataTransferAudition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_student_enrollment_id', models.PositiveIntegerField(db_index=True)),
            ],
        ),
    ]
